################################################################################
#
#  Copyright (C) 2022-2025 Garrett Brown
#  This file is part of OASIS - https://github.com/eigendude/OASIS
#
#  SPDX-License-Identifier: Apache-2.0 AND BSD-3-Clause
#  See DOCS/LICENSING.md for more information.
#
################################################################################

#
# An accelerometer on a peripheral
#

# The name of the accelerometer
string name

# The x coordinate in the closed interval [-1, 1]
float32 x

# The y coordinate in the closed interval [-1, 1]
float32 y

# The z coordinate in the closed interval [-1, 1]
float32 z
