################################################################################
#
#  Copyright (C) 2025 Garrett Brown
#  This file is part of OASIS - https://github.com/eigendude/OASIS
#
#  SPDX-License-Identifier: Apache-2.0
#  See DOCS/LICENSING.md for more information.
#
################################################################################

# Sample count
uint32 sample_count

# Flag for when enough samples have been collected
bool good_enough

# Flag for when calibration has been performed
bool calibrated

# Flag for when calibration has been uploaded to the camera
bool uploaded
