################################################################################
#
#  Copyright (C) 2022-2024 Garrett Brown
#  This file is part of OASIS - https://github.com/eigendude/OASIS
#
#  SPDX-License-Identifier: Apache-2.0 AND BSD-3-Clause
#  See DOCS/LICENSING.md for more information.
#
################################################################################

#
# A digital button on a peripheral
#

# The name of the button
string name

# The state of the feature, 0 for unpressed, 1 for pressed
uint8 pressed
