################################################################################
#
#  Copyright (C) 2026 Garrett Brown
#  This file is part of OASIS - https://github.com/eigendude/OASIS
#
#  SPDX-License-Identifier: Apache-2.0
#  See DOCS/LICENSING.md for more information.
#
################################################################################

#
# Constants for helipad guidance modes
#

# Helipad guidance is disabled and both LED pairs are off
uint8 DISABLED=0

# Helipad guidance animation is active
uint8 GUIDANCE=1

# Helicopter is landed and both LED pairs are off
uint8 LANDED=2
