################################################################################
#
#  Copyright (C) 2022-2024 Garrett Brown
#  This file is part of OASIS - https://github.com/eigendude/OASIS
#
#  SPDX-License-Identifier: Apache-2.0
#  See DOCS/LICENSING.md for more information.
#
################################################################################

#
# Available I2C devices to use with internal drivers
#

# CCS811 air quality sensor
uint8 CCS811=0

# MPU6050 IMU sensor
uint8 MPU6050=1
