################################################################################
#
#  Copyright (C) 2022-2023 Garrett Brown
#  This file is part of OASIS - https://github.com/eigendude/OASIS
#
#  SPDX-License-Identifier: Apache-2.0
#  See DOCS/LICENSING.md for more information.
#
################################################################################

#
# I2C-specific data
#

# The I2C device type, specified by a constant in I2CDeviceType.msg
uint8 i2c_device_type

# I2C port
uint8 i2c_port

# I2C address
uint8 i2c_address
