################################################################################
#
#  Copyright (C) 2025 Garrett Brown
#  This file is part of OASIS - https://github.com/eigendude/OASIS
#
#  SPDX-License-Identifier: Apache-2.0
#  See DOCS/LICENSING.md for more information.
#
################################################################################

#
# A single 3D landmark in normalized image coordinates
#

# Normalized x [0..1], left -> right
float32 x

# Normalized y [0..1], top -> down
float32 y

# Normalized depth (model‑relative units)
float32 z
