################################################################################
#
#  Copyright (C) 2022-2024 Garrett Brown
#  This file is part of OASIS - https://github.com/eigendude/OASIS
#
#  SPDX-License-Identifier: Apache-2.0
#  See DOCS/LICENSING.md for more information.
#
################################################################################

#
# Constants for peripherals
#

# Peripheral is an unknown type
uint8 TYPE_UNKNOWN=0

# Peripheral is a joystick
uint8 TYPE_JOYSTICK=1

# Peripheral is a keyboard
uint8 TYPE_KEYBOARD=2

# Peripheral is a mouse
uint8 TYPE_MOUSE=3
