################################################################################
#
#  Copyright (C) 2021-2025 Garrett Brown
#  This file is part of OASIS - https://github.com/eigendude/OASIS
#
#  SPDX-License-Identifier: Apache-2.0
#  See DOCS/LICENSING.md for more information.
#
################################################################################

################################################################################
# List of peripherals attached to the machine
################################################################################

std_msgs/Header header

PeripheralInfo[] peripherals
