################################################################################
#
#  Copyright (C) 2021-2024 Garrett Brown
#  This file is part of OASIS - https://github.com/eigendude/OASIS
#
#  SPDX-License-Identifier: Apache-2.0
#  See DOCS/LICENSING.md for more information.
#
################################################################################

#
# Information about known serial port devices
#

# The timestamp of the scan
std_msgs/Header header

# The detected serial port devices
SerialDevice[] serial_devices
