################################################################################
#
#  Copyright (C) 2022-2023 Garrett Brown
#  This file is part of OASIS - https://github.com/eigendude/OASIS
#
#  SPDX-License-Identifier: Apache-2.0 AND BSD-3-Clause
#  See DOCS/LICENSING.md for more information.
#
################################################################################

#
# A throttle on a peripheral
#

# The name of the throttle
string name

# The position in the closed interval [-1, 1], as the throttle moves from fully
# down to fully up
float32 position
