################################################################################
#
#  Copyright (C) 2025 Garrett Brown
#  This file is part of OASIS - https://github.com/eigendude/OASIS
#
#  SPDX-License-Identifier: Apache-2.0
#  See DOCS/LICENSING.md for more information.
#
################################################################################

float32 input_voltage
float32 output_voltage
int32 battery_charge
int32 battery_runtime
int32 load_percent
string status
