################################################################################
#
#  Copyright (C) 2022-2024 Garrett Brown
#  This file is part of OASIS - https://github.com/eigendude/OASIS
#
#  SPDX-License-Identifier: Apache-2.0 AND BSD-3-Clause
#  See DOCS/LICENSING.md for more information.
#
################################################################################

#
# A steering wheel on a peripheral
#

# The name of the steering wheel
string name

# The position in the closed interval [-1, 1], as the wheel moves from fully
# left to fully right
float32 position
