[mypy]
mypy_path =
    $MYPY_CONFIG_FILE_DIR/oasis_control:
    $MYPY_CONFIG_FILE_DIR/oasis_drivers_py:
    $MYPY_CONFIG_FILE_DIR/oasis_home:
    $MYPY_CONFIG_FILE_DIR/oasis_perception_py:
    $MYPY_CONFIG_FILE_DIR/ros-ws/oasis-${ROS2_DISTRO}/install/lib/python3.12/site-packages

[mypy-ament_index_python.*]
ignore_missing_imports = True

[mypy-apriltag_msgs.*]
ignore_missing_imports = True

[mypy-builtin_interfaces.msg]
ignore_missing_imports = True

[mypy-camera_calibration.*]
ignore_missing_imports = True

[mypy-cv2]
ignore_missing_imports = True

[mypy-cv_bridge]
ignore_missing_imports = True

[mypy-geometry_msgs.msg]
ignore_missing_imports = True

[mypy-image_transport_py]
ignore_missing_imports = True

[mypy-launch.*]
ignore_missing_imports = True

[mypy-launch_ros.*]
ignore_missing_imports = True

[mypy-mediapipe.*]
ignore_missing_imports = True

[mypy-message_filters]
ignore_missing_imports = True

[mypy-nav_msgs.*]
ignore_missing_imports = True

[mypy-oasis_msgs.*]
follow_imports = skip

[mypy-pymata_express.*]
ignore_missing_imports = True

[mypy-rclpy.*]
ignore_missing_imports = True

[mypy-sensor_msgs.*]
ignore_missing_imports = True

[mypy-std_msgs.msg]
ignore_missing_imports = True

[mypy-telemetrix_aio]
ignore_missing_imports = True

[mypy-tf2_ros]
ignore_missing_imports = True
