/*
 *  Copyright (C) 2026 Garrett Brown
 *  This file is part of OASIS - https://github.com/eigendude/OASIS
 *
 *  SPDX-License-Identifier: Apache-2.0
 *  See the file LICENSE.txt for more information.
 */

#pragma once

#include "imu/ImuTypes.h"

#include <array>
#include <cstddef>
#include <cstdint>

namespace OASIS::IMU::BNO086
{
/*!\brief Sensor report identifiers from SH-2 sensor hub protocol */
enum class ReportId : std::uint8_t
{
  Accelerometer = 0x01,
  GyroscopeCalibrated = 0x02,
  LinearAcceleration = 0x04,
  RotationVector = 0x05,
  Gravity = 0x06,
};

/*!\brief Sensor event decoded from one BNO086 report payload */
struct SensorEvent
{
  /*!
   * \brief Report identifier from the sensor-hub stream
   *
   * Units: enum code
   */
  ReportId report_id{ReportId::Accelerometer};

  /*!
   * \brief Status field from the report header
   *
   * Units: bit-field
   */
  std::uint8_t status{0};

  /*!
   * \brief Sequence number from the sensor report payload
   *
   * Units: counter ticks
   */
  std::uint8_t sequence{0};

  /*!
   * \brief Parsed SH-2 accuracy bits from \ref status
   *
   * Units: enum code in range [0, 3]
   */
  std::uint8_t accuracy{0};

  /*!
   * \brief Delay from timebase reference to event sample time
   *
   * Units: 100 us ticks, expected range [0, 16383]
   */
  std::uint16_t delay_ticks{0};

  /*!
   * \brief Delay from timebase reference to event sample time
   *
   * Units: microseconds, computed as \ref delay_ticks * 100
   */
  std::uint32_t delay_us{0};

  /*!
   * \brief True when \ref delay_us was present in the payload
   */
  bool has_delay{false};

  /*!
   * \brief Timebase Reference delta associated with this event
   *
   * Units: signed 100 us ticks. Host timebase = interrupt - delta.
   */
  std::int32_t timebase_delta_ticks{0};

  /*!
   * \brief True when \ref timebase_delta_ticks was present in the payload
   */
  bool has_timebase_reference{false};

  /*!
   * \brief SHTP channel that carried this decoded report
   *
   * Units: SHTP channel number
   */
  std::uint8_t channel{0};

  /*!
   * \brief Offset of this report inside the decoded SHTP payload
   *
   * Units: bytes from the start of the payload
   */
  std::size_t report_offset{0};

  /*!
   * \brief Number of payload bytes consumed by this report record
   *
   * Units: bytes including the SH-2 sensor report header and values
   */
  std::size_t bytes_consumed{0};

  /*!
   * \brief Raw Q-format values carried by this report
   *
   * Units: report specific fixed-point values
   */
  std::array<std::int16_t, 5> values{};
};

/*!\brief Requested SH-2 feature configuration for one sensor report */
struct FeatureConfiguration
{
  /*!
   * \brief Sensor report being configured
   *
   * Units: enum code
   */
  ReportId report_id{ReportId::Accelerometer};

  /*!
   * \brief Requested time between generated reports
   *
   * Units: microseconds, zero when the report is disabled
   */
  std::uint32_t requested_interval_us{10'000};

  /*!
   * \brief Requested maximum batching delay before host delivery
   *
   * Units: microseconds, zero disables batching
   */
  std::uint32_t requested_batch_interval_us{0};

  /*!
   * \brief True when the report should be generated by the device
   */
  bool enabled{true};
};

/*!\brief Feature response decoded from an SH-2 Get Feature Response packet */
struct FeatureResponse
{
  /*!
   * \brief Sensor report described by this response
   *
   * Units: enum code
   */
  ReportId report_id{ReportId::Accelerometer};

  /*!
   * \brief Feature flags accepted by the BNO08X
   *
   * Units: bit-field
   */
  std::uint8_t feature_flags{0};

  /*!
   * \brief Change threshold configured for reports that support it
   *
   * Units: report specific fixed-point threshold
   */
  std::uint16_t change_sensitivity{0};

  /*!
   * \brief Actual time between generated reports returned by the device
   *
   * Units: microseconds, zero when the report is disabled
   */
  std::uint32_t report_interval_us{0};

  /*!
   * \brief Actual maximum batch delay returned by the device
   *
   * Units: microseconds
   */
  std::uint32_t batch_interval_us{0};

  /*!
   * \brief Sensor-specific configuration word returned by the device
   *
   * Units: report specific bit-field
   */
  std::uint32_t sensor_specific_config{0};
};

inline bool IsFeatureBatchingActive(const FeatureResponse& response)
{
  return response.batch_interval_us > 0;
}

/*!
 * \brief Rotation Vector payload slots after the 4-byte SH-2 sensor header
 *
 * The BNO08X datasheet's Rotation Vector metadata declares quaternion samples
 * at Q14 and the additional accuracy field at Q12. The SH-2 Rotation Vector
 * input report then maps those five signed 16-bit values to payload bytes
 * 4-13 as quaternion i/j/k/real followed by the accuracy estimate.
 */
enum class RotationVectorValueIndex : std::size_t
{
  QuaternionI = 0,
  QuaternionJ = 1,
  QuaternionK = 2,
  QuaternionReal = 3,
  AccuracyEstimate = 4,
};

/*!\brief Incremental fused sample cache built from BNO086 events */
struct ImuSampleFrame
{
  /*!
   * \brief True when orientation quaternion is updated
   */
  bool has_orientation{false};

  /*!
   * \brief True when calibrated gyroscope sample is updated
   */
  bool has_gyro{false};

  /*!
   * \brief True when gravity-removed linear acceleration is updated
   */
  bool has_linear_accel{false};

  /*!
   * \brief True when gravity-included acceleration is updated
   */
  bool has_accel{false};

  /*!
   * \brief True when gravity vector is updated
   */
  bool has_gravity{false};

  /*!
   * \brief Orientation quaternion in IMU frame
   *
   * Order: x, y, z, w
   * Units: unitless
   */
  std::array<double, 4> orientation_xyzw{0.0, 0.0, 0.0, 1.0};

  /*!
   * \brief Calibrated angular velocity from BNO086 gyroscope
   *
   * Units: rad/s
   */
  Vec3 gyro_rads{0.0, 0.0, 0.0};

  /*!
   * \brief Gravity-removed acceleration from BNO086 linear accel report
   *
   * Units: m/s^2
   */
  Vec3 linear_accel_mps2{0.0, 0.0, 0.0};

  /*!
   * \brief Gravity-included acceleration from calibrated accel report
   *
   * Units: m/s^2
   */
  Vec3 accel_mps2{0.0, 0.0, 0.0};

  /*!
   * \brief Gravity vector estimated by BNO086 fusion stack
   *
   * Units: m/s^2
   */
  Vec3 gravity_mps2{0.0, 0.0, 0.0};

  /*!
   * \brief Orientation covariance in row-major 3x3 layout
   *
   * Units: rad^2
   */
  Mat3 orientation_cov_rad2{};

  /*!
   * \brief Angular velocity covariance in row-major 3x3 layout
   *
   * Units: (rad/s)^2
   */
  Mat3 gyro_cov_rads2_2{};

  /*!
   * \brief Linear acceleration covariance in row-major 3x3 layout
   *
   * Units: (m/s^2)^2
   */
  Mat3 linear_accel_cov_mps2_2{};

  /*!
   * \brief Calibrated acceleration covariance in row-major 3x3 layout
   *
   * Units: (m/s^2)^2
   */
  Mat3 accel_cov_mps2_2{};

  /*!
   * \brief Gravity covariance in row-major 3x3 layout
   *
   * Units: (m/s^2)^2
   */
  Mat3 gravity_cov_mps2_2{};

  /*!
   * \brief True when orientation covariance is populated
   */
  bool has_orientation_covariance{false};

  /*!
   * \brief True when gyro covariance is populated
   */
  bool has_gyro_covariance{false};

  /*!
   * \brief True when linear acceleration covariance is populated
   */
  bool has_linear_accel_covariance{false};

  /*!
   * \brief True when calibrated acceleration covariance is populated
   */
  bool has_accel_covariance{false};

  /*!
   * \brief True when gravity covariance is populated
   */
  bool has_gravity_covariance{false};
};

constexpr std::uint8_t kShtpReportBaseTimestamp = 0xFB;
constexpr std::uint8_t kShtpReportTimestampRebase = 0xFA;
constexpr std::uint8_t kShtpGetFeatureResponse = 0xFC;
constexpr std::uint8_t kShtpSetFeatureCommand = 0xFD;
constexpr std::uint8_t kShtpGetFeatureRequest = 0xFE;
} // namespace OASIS::IMU::BNO086
