################################################################################
#
#  Copyright (C) 2026 Garrett Brown
#  This file is part of OASIS - https://github.com/eigendude/OASIS
#
#  SPDX-License-Identifier: Apache-2.0
#  See DOCS/LICENSING.md for more information.
#
################################################################################

#
# Attach and configure a helipad feature on the microcontroller
#

# Analog IR sensor pin number (ex. A2 on the Arduino is specified as 2)
uint32 ir_pin

# PWM pin for LED pair A
uint32 led_pair_a_pin

# PWM pin for LED pair B
uint32 led_pair_b_pin

---
