################################################################################
#
#  Copyright (C) 2025 Garrett Brown
#  This file is part of OASIS - https://github.com/eigendude/OASIS
#
#  SPDX-License-Identifier: Apache-2.0
#  See DOCS/LICENSING.md for more information.
#
################################################################################

# Unique identifier for the RGB light source
string light_id

# Red value, in the range [0, 1]
float32 r

# Green value, in the range [0, 1]
float32 g

# Blue value, in the range [0, 1]
float32 b

---
