################################################################################
#
#  Copyright (C) 2025 Garrett Brown
#  This file is part of OASIS - https://github.com/eigendude/OASIS
#
#  SPDX-License-Identifier: Apache-2.0
#  See DOCS/LICENSING.md for more information.
#
################################################################################

#
# Defines the Wake-on-LAN command service.
#

# Target machine MAC address (e.g. "AA:BB:CC:DD:EE:FF")
string mac_address

---
