name: Prettier Code Formatter

# Controls when the action will run. Triggers the workflow on push or pull
# request events
on: [push, pull_request]

jobs:
  prettier:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            node_version: 20

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node_version }}'

      - name: Cache pnpm modules
        id: cache-pnpm-modules
        uses: actions/cache@v4
        with:
          path: oasis_visualization/node_modules
          key: ${{ runner.os }}-${{ matrix.node_version }}-pnpm-${{ hashFiles('oasis_visualization/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node_version }}-pnpm-

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        if: steps.cache-pnpm-modules.outputs.cache-hit != 'true'
        run: pnpm install
        working-directory: oasis_visualization

      - name: Run linter
        run: pnpm lint
        working-directory: oasis_visualization
